# Generated by Django 4.0.4 on 2022-05-07 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dongdongapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('post_date', models.DateTimeField()),
                ('required_number', models.IntegerField(default=1)),
                ('gender', models.CharField(max_length=10)),
                ('exercise', models.CharField(max_length=10)),
                ('exercise_skil', models.IntegerField(default=1)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
